### ISSUE TITLE
implement `puzzlefs extract` code too?

### ISSUE THREAD

**Issue by tych0** [anuvu/puzzlefs#12]
I'm not sure if this one is really that useful, but let's see.

It may be useful to have something that does actually extract a puzzlefs image onto a filesystem instead of just being able to mount it. Given that we can do fuse mounts as unprivileged users, people could always just mount the image, but maybe there's some case where it would be useful to extract things too (even if only for debugging).

We could implement this entirely in terms of operations on our `fuse::Filesystem` trait so we get it "for free" minus the traversal bits.

**Comment by tych0** [comment]
This is in progress as part of #23

**Comment by ariel-miculas** [comment]
extended attributes are extracted in this PR: https://github.com/anuvu/puzzlefs/pull/38

**Comment by ariel-miculas** [comment]
permissions and ownership are implemented in https://github.com/anuvu/puzzlefs/pull/39

**Comment by ariel-miculas** [comment]
@hallyn can this issue be closed or is there anything else you'd like implemented?

**Comment by hallyn** [comment]
Thanks - let's close it, and open new issues if we find other shortcomings.
