### ISSUE TITLE
implement compression

### ISSUE THREAD

**Issue by tych0** [anuvu/puzzlefs#14]
Right now all the metadata and file contents for puzzlefs are uncompressed. We should compress them.

The design format of puzzlefs constrains the use of compression a bit though: we need to be able to read data from an arbitrary offset (the compression community calls this a "seekable compression format").

People like zstd as a compression format, and it has out-of-tree implementations of this with rust bindings:

https://github.com/facebook/zstd/blob/dev/contrib/seekable_format/zstd_seekable_compression_format.md
https://crates.io/crates/zstd-seekable

which may be interesting.

**Comment by tych0** [comment]
We have some basic support for this now with d52efd2b805885e35e089ae4b33177dff13b0b93; let's see how it goes.

**Comment by ariel-miculas** [comment]
[from squashfs](https://dr-emann.github.io/squashfs/squashfs.html#_compression_options)
> For fast random access, compressed files are split up in fixed size blocks that are compressed separately. The block size can be set between 4k and 1M (default for squashfs-tools and squashfs-tools-ng is 128K).

[from zstd_seekable](https://github.com/facebook/zstd/blob/dev/contrib/seekable_format/zstd_seekable_compression_format.md)
> This is done by splitting up the input data into frames, each of which are compressed independently, and so can be decompressed independently. Decompression then takes advantage of a provided 'seek table', which allows the decompressor to immediately jump to the desired data.

Depending on the chunking parameters we choose, the seekable compression may not be worth it. For example, let's say we pick 16KB for the average chunk and 64KB for the maximum chunk. Then the maximum chunk size is less than the squashfs default block size of 128KB. Also, zstd seekable compression includes extra metadata for storing information about the offsets, resulting in a size increase for the compressed chunks. Plus we'll be stuck with zstd.

**Comment by hallyn** [comment]
Could you post your deduplication performance results, or maybe just a concise summary?

IIUC, tuning the parameters made it so that indeed compression may not be needed.

**Comment by ariel-miculas** [comment]
I still think we need compression, I'm only arguing against seekable compression.

**Comment by hallyn** [comment]
Sounds good.

**Comment by ariel-miculas** [comment]
An interesting point from squashfs is that they're not compressing blocks if this would result in a larger size, in this case they're storing the block uncompressed, perhaps we should also implement this.

**Comment by ariel-miculas** [comment]
Related: https://github.com/containers/image/pull/1084

**Comment by ariel-miculas** [comment]
We can have optional support for compression and we need a new field in BlobRef to indicate whether the blob is compressed or not. The blob still needs to be content-addressed, so the sha256sum of the compressed blob needs to be computed.

**Comment by ariel-miculas** [comment]
We should also process the files in parallel during puzzlefs build in order to speed up the compression.

**Comment by ariel-miculas** [comment]
## Setup:
Build and mount the filesystem:
```
target/release/puzzlefs build ../test-puzzlefs/real_rootfs/barehost/rootfs /tmp/oci-barehost test
target/release/puzzlefs mount -f /tmp/oci-barehost test /tmp/puzzle
```
Reading an entire filesystem:
## Compression disabled
```
$ time fd -tf -x cat > /dev/null
fd -tf -x cat > /dev/null  9.64s user 2.54s system 280% cpu 4.338 total
```
## Compression enabled
```
$ time fd -tf -x cat > /dev/null
fd -tf -x cat > /dev/null  8.59s user 2.13s system 57% cpu 18.549 total
```
