### ISSUE TITLE
implement the "real" wire format

### ISSUE THREAD

**Issue by tych0** [anuvu/puzzlefs#18]
Right now we're using serde_cbor to serialize things, and e.g. in structures it puts essentially a json map with a string of the field name in. That's useful to get us off the ground, but we should implement a real serialization for our objects so we get smaller representations of them.

**Comment by tych0** [comment]
related: right now `MetadatBlob::find_inode` parses the entire inode list, and then does a subsequent on-disk binary search to find the real inode. That sucks and this would fix it :)

**Comment by ariel-miculas** [comment]
possible alternative: https://github.com/bincode-org/bincode

**Comment by ariel-miculas** [comment]
The `find_inode` no longer reads the entire inode list into memory as of https://github.com/anuvu/puzzlefs/pull/49

**Comment by ariel-miculas** [comment]
Hey @tych0, did you have any alternatives to cbor in mind for the puzzlefs wire format?

**Comment by ariel-miculas** [comment]
[capnproto](https://github.com/capnproto/capnproto-rust) was also mentioned by Kent Overstreet [here](https://lore.kernel.org/rust-for-linux/ZIPDCGM9HbPhR2yW@moria.home.lan/)

**Comment by tych0** [comment]
My understanding is that capnproto has pretty good encoding/decoding optimizations over e.g. protobuf, so it seems like a reasonable suggestion.
