### ISSUE TITLE
Switch to upstream fs-verity-rs

### ISSUE THREAD

**Issue by rvolgers** [anuvu/puzzlefs#91]
Regarding this:

https://github.com/rvolgers/puzzlefs/blob/ad914960d6e082804a4431bb407887c9bcdb16d4/fsverity_helpers/Cargo.toml#L12

I just merged the pull request (https://github.com/rvolgers/fs-verity-rs/pull/2) and published a new version, so you should be able to use that directly.

**Comment by ariel-miculas** [comment]
Nice, thank you!
